/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2021-08-17 08:49:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.egovframework.example.join;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <!-- meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0\"/ -->\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <title>회원가입</title>\r\n");
      out.write("        <!-- Bootstrap -->\r\n");
      out.write("        <!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("		<link href=\"/resources/image/icon/HalfLife.ico\" rel=\"shortcuticon\">\r\n");
      out.write("		<!-- 부가적인 테마 -->\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("		<!-- jQuery (부트스트랩의 자바스크립트 플러그인을 위해 필요한) -->\r\n");
      out.write("        <script src=\"http://code.jquery.com/jquery.js\"></script>\r\n");
      out.write("		<!-- 합쳐지고 최소화된 최신 자바스크립트 -->\r\n");
      out.write("		<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"container\"><!-- 좌우측의 공간 확보 -->\r\n");
      out.write("            <!-- 헤더 들어가는 부분 -->\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <p></p>\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <small>\r\n");
      out.write("                    <a href=\"#\">로그인</a> | <a href=\"#\">회원가입</a>\r\n");
      out.write("                    </small>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--// 헤더 들어가는 부분 -->\r\n");
      out.write("            <!-- 모달창 -->\r\n");
      out.write("            <div class=\"modal fade\" id=\"defaultModal\">\r\n");
      out.write("                <div class=\"modal-dialog\">\r\n");
      out.write("                    <div class=\"modal-content\">\r\n");
      out.write("                        <div class=\"modal-header\">\r\n");
      out.write("                            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">×</button>\r\n");
      out.write("                            <h4 class=\"modal-title\">알림</h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"modal-body\">\r\n");
      out.write("                            <p class=\"modal-contents\"></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"modal-footer\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div><!-- /.modal-content -->\r\n");
      out.write("                </div><!-- /.modal-dialog -->\r\n");
      out.write("            </div><!-- /.modal -->\r\n");
      out.write("            <!--// 모달창 -->\r\n");
      out.write("            <hr/>\r\n");
      out.write("            <!-- 본문 들어가는 부분 -->\r\n");
      out.write("                \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("            <form class=\"form-horizontal\" role=\"form\" method=\"post\" action=\"javascript:alert( 'success!' );\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"provision\" class=\"col-lg-2 control-label\">회원가입약관</label>\r\n");
      out.write("                    <div class=\"col-lg-10\" id=\"provision\">\r\n");
      out.write("                        <textarea class=\"form-control\" rows=\"8\" style=\"resize:none\">약관동의\r\n");
      out.write("블라블라블라블라블라블라블라블라블라블라블라블라\r\n");
      out.write("블라블라블라블라블라블라블라블라블라블라블라블라\r\n");
      out.write("블라블라블라블라블라블라블라블라블라블라블라블라.................\r\n");
      out.write("                        </textarea>\r\n");
      out.write("                        <div class=\"radio\">\r\n");
      out.write("                            <label>\r\n");
      out.write("                                <input type=\"radio\" id=\"provisionYn\" name=\"provisionYn\" value=\"Y\" autofocus=\"autofocus\" checked>\r\n");
      out.write("                                동의합니다.\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"radio\">\r\n");
      out.write("                            <label>\r\n");
      out.write("                                <input type=\"radio\" id=\"provisionYn\" name=\"provisionYn\" value=\"N\">\r\n");
      out.write("                                동의하지 않습니다.\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"memberInfo\" class=\"col-lg-2 control-label\">개인정보취급방침</label>\r\n");
      out.write("                    <div class=\"col-lg-10\" id=\"memberInfo\">\r\n");
      out.write("                        <textarea class=\"form-control\" rows=\"8\" style=\"resize:none\">개인정보의 항목 및 수집방법\r\n");
      out.write("블라블라블라블라블라블라블라블라블라블라블라블라                        \r\n");
      out.write("블라블라블라블라블라블라블라블라블라블라블라블라\r\n");
      out.write("블라블라블라블라블라블라블라블라블라블라블라블라.................\r\n");
      out.write("                        </textarea>\r\n");
      out.write("                        <div class=\"radio\">\r\n");
      out.write("                            <label>\r\n");
      out.write("                                <input type=\"radio\" id=\"memberInfoYn\" name=\"memberInfoYn\" value=\"Y\" checked>\r\n");
      out.write("                                동의합니다.\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"radio\">\r\n");
      out.write("                            <label>\r\n");
      out.write("                                <input type=\"radio\" id=\"memberInfoYn\" name=\"memberInfoYn\" value=\"N\">\r\n");
      out.write("                                동의하지 않습니다.\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\" id=\"divId\">\r\n");
      out.write("                    <label for=\"inputId\" class=\"col-lg-2 control-label\">아이디</label>\r\n");
      out.write("                    <div class=\"col-lg-10\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control onlyAlphabetAndNumber\" id=\"id\" data-rule-required=\"true\" placeholder=\"30자이내의 알파벳, 언더스코어(_), 숫자만 입력 가능합니다.\" maxlength=\"30\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\" id=\"divPassword\">\r\n");
      out.write("                    <label for=\"inputPassword\" class=\"col-lg-2 control-label\">패스워드</label>\r\n");
      out.write("                    <div class=\"col-lg-10\">\r\n");
      out.write("                        <input type=\"password\" class=\"form-control\" id=\"password\" name=\"excludeHangul\" data-rule-required=\"true\" placeholder=\"패스워드\" maxlength=\"30\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\" id=\"divPasswordCheck\">\r\n");
      out.write("                    <label for=\"inputPasswordCheck\" class=\"col-lg-2 control-label\">패스워드 확인</label>\r\n");
      out.write("                    <div class=\"col-lg-10\">\r\n");
      out.write("                        <input type=\"password\" class=\"form-control\" id=\"passwordCheck\" data-rule-required=\"true\" placeholder=\"패스워드 확인\" maxlength=\"30\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\" id=\"divName\">\r\n");
      out.write("                    <label for=\"inputName\" class=\"col-lg-2 control-label\">이름</label>\r\n");
      out.write("                    <div class=\"col-lg-10\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control onlyHangul\" id=\"name\" data-rule-required=\"true\" placeholder=\"한글만 입력 가능합니다.\" maxlength=\"15\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"form-group\" id=\"divNickname\">\r\n");
      out.write("                    <label for=\"inputNickname\" class=\"col-lg-2 control-label\">별명</label>\r\n");
      out.write("                    <div class=\"col-lg-10\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"nickname\" data-rule-required=\"true\" placeholder=\"별명\" maxlength=\"15\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"form-group\" id=\"divEmail\">\r\n");
      out.write("                    <label for=\"inputEmail\" class=\"col-lg-2 control-label\">이메일</label>\r\n");
      out.write("                    <div class=\"col-lg-10\">\r\n");
      out.write("                        <input type=\"email\" class=\"form-control\" id=\"email\" data-rule-required=\"true\" placeholder=\"이메일\" maxlength=\"40\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\" id=\"divPhoneNumber\">\r\n");
      out.write("                    <label for=\"inputPhoneNumber\" class=\"col-lg-2 control-label\">휴대폰 번호</label>\r\n");
      out.write("                    <div class=\"col-lg-10\">\r\n");
      out.write("                        <input type=\"tel\" class=\"form-control onlyNumber\" id=\"phoneNumber\" data-rule-required=\"true\" placeholder=\"-를 제외하고 숫자만 입력하세요.\" maxlength=\"11\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"inputPhoneNumber\" class=\"col-lg-2 control-label\">성별</label>\r\n");
      out.write("                    <div class=\"col-lg-10\">\r\n");
      out.write("                        <select class=\"form-control\" id=\"gender\">\r\n");
      out.write("                            <option value=\"M\">남</option>\r\n");
      out.write("                            <option value=\"F\">여</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"inputEmailReceiveYn\" class=\"col-lg-2 control-label\">이메일 수신여부</label>\r\n");
      out.write("                    <div class=\"col-lg-10\">\r\n");
      out.write("                        <label class=\"radio-inline\">\r\n");
      out.write("                            <input type=\"radio\" id=\"emailReceiveYn\" name=\"emailReceiveYn\" value=\"Y\" checked> 동의합니다.\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <label class=\"radio-inline\">\r\n");
      out.write("                            <input type=\"radio\" id=\"emailReceiveYn\" name=\"emailReceiveYn\" value=\"N\"> 동의하지 않습니다.\r\n");
      out.write("                        </label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"inputPhoneNumber\" class=\"col-lg-2 control-label\">SMS 수신여부</label>\r\n");
      out.write("                    <div class=\"col-lg-10\">\r\n");
      out.write("                        <label class=\"radio-inline\">\r\n");
      out.write("                            <input type=\"radio\" id=\"smsReceiveYn\" name=\"smsReceiveYn\" value=\"Y\" checked> 동의합니다.\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <label class=\"radio-inline\">\r\n");
      out.write("                            <input type=\"radio\" id=\"smsReceiveYn\" name=\"smsReceiveYn\" value=\"N\"> 동의하지 않습니다.\r\n");
      out.write("                        </label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <div class=\"col-lg-offset-2 col-lg-10\">\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary\">Sign in</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <script>\r\n");
      out.write("        \r\n");
      out.write("            $(function(){\r\n");
      out.write("                //모달을 전역변수로 선언\r\n");
      out.write("                var modalContents = $(\".modal-contents\");\r\n");
      out.write("                var modal = $(\"#defaultModal\");\r\n");
      out.write("                \r\n");
      out.write("                $('.onlyAlphabetAndNumber').keyup(function(event){\r\n");
      out.write("                    if (!(event.keyCode >=37 && event.keyCode<=40)) {\r\n");
      out.write("                        var inputVal = $(this).val();\r\n");
      out.write("                        $(this).val($(this).val().replace(/[^_a-z0-9]/gi,'')); //_(underscore), 영어, 숫자만 가능\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                $(\".onlyHangul\").keyup(function(event){\r\n");
      out.write("                    if (!(event.keyCode >=37 && event.keyCode<=40)) {\r\n");
      out.write("                        var inputVal = $(this).val();\r\n");
      out.write("                        $(this).val(inputVal.replace(/[a-z0-9]/gi,''));\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            \r\n");
      out.write("                $(\".onlyNumber\").keyup(function(event){\r\n");
      out.write("                    if (!(event.keyCode >=37 && event.keyCode<=40)) {\r\n");
      out.write("                        var inputVal = $(this).val();\r\n");
      out.write("                        $(this).val(inputVal.replace(/[^0-9]/gi,''));\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                //------- 검사하여 상태를 class에 적용\r\n");
      out.write("                $('#id').keyup(function(event){\r\n");
      out.write("                    \r\n");
      out.write("                    var divId = $('#divId');\r\n");
      out.write("                    \r\n");
      out.write("                    if($('#id').val()==\"\"){\r\n");
      out.write("                        divId.removeClass(\"has-success\");\r\n");
      out.write("                        divId.addClass(\"has-error\");\r\n");
      out.write("                    }else{\r\n");
      out.write("                        divId.removeClass(\"has-error\");\r\n");
      out.write("                        divId.addClass(\"has-success\");\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                $('#password').keyup(function(event){\r\n");
      out.write("                    \r\n");
      out.write("                    var divPassword = $('#divPassword');\r\n");
      out.write("                    \r\n");
      out.write("                    if($('#password').val()==\"\"){\r\n");
      out.write("                        divPassword.removeClass(\"has-success\");\r\n");
      out.write("                        divPassword.addClass(\"has-error\");\r\n");
      out.write("                    }else{\r\n");
      out.write("                        divPassword.removeClass(\"has-error\");\r\n");
      out.write("                        divPassword.addClass(\"has-success\");\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                $('#passwordCheck').keyup(function(event){\r\n");
      out.write("                    \r\n");
      out.write("                    var passwordCheck = $('#passwordCheck').val();\r\n");
      out.write("                    var password = $('#password').val();\r\n");
      out.write("                    var divPasswordCheck = $('#divPasswordCheck');\r\n");
      out.write("                    \r\n");
      out.write("                    if((passwordCheck==\"\") || (password!=passwordCheck)){\r\n");
      out.write("                        divPasswordCheck.removeClass(\"has-success\");\r\n");
      out.write("                        divPasswordCheck.addClass(\"has-error\");\r\n");
      out.write("                    }else{\r\n");
      out.write("                        divPasswordCheck.removeClass(\"has-error\");\r\n");
      out.write("                        divPasswordCheck.addClass(\"has-success\");\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                $('#name').keyup(function(event){\r\n");
      out.write("                    \r\n");
      out.write("                    var divName = $('#divName');\r\n");
      out.write("                    \r\n");
      out.write("                    if($.trim($('#name').val())==\"\"){\r\n");
      out.write("                        divName.removeClass(\"has-success\");\r\n");
      out.write("                        divName.addClass(\"has-error\");\r\n");
      out.write("                    }else{\r\n");
      out.write("                        divName.removeClass(\"has-error\");\r\n");
      out.write("                        divName.addClass(\"has-success\");\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                $('#nickname').keyup(function(event){\r\n");
      out.write("                    \r\n");
      out.write("                    var divNickname = $('#divNickname');\r\n");
      out.write("                    \r\n");
      out.write("                    if($.trim($('#nickname').val())==\"\"){\r\n");
      out.write("                        divNickname.removeClass(\"has-success\");\r\n");
      out.write("                        divNickname.addClass(\"has-error\");\r\n");
      out.write("                    }else{\r\n");
      out.write("                        divNickname.removeClass(\"has-error\");\r\n");
      out.write("                        divNickname.addClass(\"has-success\");\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                $('#email').keyup(function(event){\r\n");
      out.write("                    \r\n");
      out.write("                    var divEmail = $('#divEmail');\r\n");
      out.write("                    \r\n");
      out.write("                    if($.trim($('#email').val())==\"\"){\r\n");
      out.write("                        divEmail.removeClass(\"has-success\");\r\n");
      out.write("                        divEmail.addClass(\"has-error\");\r\n");
      out.write("                    }else{\r\n");
      out.write("                        divEmail.removeClass(\"has-error\");\r\n");
      out.write("                        divEmail.addClass(\"has-success\");\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                $('#phoneNumber').keyup(function(event){\r\n");
      out.write("                    \r\n");
      out.write("                    var divPhoneNumber = $('#divPhoneNumber');\r\n");
      out.write("                    \r\n");
      out.write("                    if($.trim($('#phoneNumber').val())==\"\"){\r\n");
      out.write("                        divPhoneNumber.removeClass(\"has-success\");\r\n");
      out.write("                        divPhoneNumber.addClass(\"has-error\");\r\n");
      out.write("                    }else{\r\n");
      out.write("                        divPhoneNumber.removeClass(\"has-error\");\r\n");
      out.write("                        divPhoneNumber.addClass(\"has-success\");\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                //------- validation 검사\r\n");
      out.write("                $( \"form\" ).submit(function( event ) {\r\n");
      out.write("                    \r\n");
      out.write("                    var provision = $('#provision');\r\n");
      out.write("                    var memberInfo = $('#memberInfo');\r\n");
      out.write("                    var divId = $('#divId');\r\n");
      out.write("                    var divPassword = $('#divPassword');\r\n");
      out.write("                    var divPasswordCheck = $('#divPasswordCheck');\r\n");
      out.write("                    var divName = $('#divName');\r\n");
      out.write("                    var divNickname = $('#divNickname');\r\n");
      out.write("                    var divEmail = $('#divEmail');\r\n");
      out.write("                    var divPhoneNumber = $('#divPhoneNumber');\r\n");
      out.write("                    \r\n");
      out.write("                    //회원가입약관\r\n");
      out.write("                    if($('#provisionYn:checked').val()==\"N\"){\r\n");
      out.write("                        modalContents.text(\"회원가입약관에 동의하여 주시기 바랍니다.\"); //모달 메시지 입력\r\n");
      out.write("                        modal.modal('show'); //모달 띄우기\r\n");
      out.write("                        \r\n");
      out.write("                        provision.removeClass(\"has-success\");\r\n");
      out.write("                        provision.addClass(\"has-error\");\r\n");
      out.write("                        $('#provisionYn').focus();\r\n");
      out.write("                        return false;\r\n");
      out.write("                    }else{\r\n");
      out.write("                        provision.removeClass(\"has-error\");\r\n");
      out.write("                        provision.addClass(\"has-success\");\r\n");
      out.write("                    }\r\n");
      out.write("                    \r\n");
      out.write("                    //개인정보취급방침\r\n");
      out.write("                    if($('#memberInfoYn:checked').val()==\"N\"){\r\n");
      out.write("                        modalContents.text(\"개인정보취급방침에 동의하여 주시기 바랍니다.\");\r\n");
      out.write("                        modal.modal('show');\r\n");
      out.write("                        \r\n");
      out.write("                        memberInfo.removeClass(\"has-success\");\r\n");
      out.write("                        memberInfo.addClass(\"has-error\");\r\n");
      out.write("                        $('#memberInfoYn').focus();\r\n");
      out.write("                        return false;\r\n");
      out.write("                    }else{\r\n");
      out.write("                        memberInfo.removeClass(\"has-error\");\r\n");
      out.write("                        memberInfo.addClass(\"has-success\");\r\n");
      out.write("                    }\r\n");
      out.write("                    \r\n");
      out.write("                    //아이디 검사\r\n");
      out.write("                    if($('#id').val()==\"\"){\r\n");
      out.write("                        modalContents.text(\"아이디를 입력하여 주시기 바랍니다.\");\r\n");
      out.write("                        modal.modal('show');\r\n");
      out.write("                        \r\n");
      out.write("                        divId.removeClass(\"has-success\");\r\n");
      out.write("                        divId.addClass(\"has-error\");\r\n");
      out.write("                        $('#id').focus();\r\n");
      out.write("                        return false;\r\n");
      out.write("                    }else{\r\n");
      out.write("                        divId.removeClass(\"has-error\");\r\n");
      out.write("                        divId.addClass(\"has-success\");\r\n");
      out.write("                    }\r\n");
      out.write("                    \r\n");
      out.write("                    //패스워드 검사\r\n");
      out.write("                    if($('#password').val()==\"\"){\r\n");
      out.write("                        modalContents.text(\"패스워드를 입력하여 주시기 바랍니다.\");\r\n");
      out.write("                        modal.modal('show');\r\n");
      out.write("                        \r\n");
      out.write("                        divPassword.removeClass(\"has-success\");\r\n");
      out.write("                        divPassword.addClass(\"has-error\");\r\n");
      out.write("                        $('#password').focus();\r\n");
      out.write("                        return false;\r\n");
      out.write("                    }else{\r\n");
      out.write("                        divPassword.removeClass(\"has-error\");\r\n");
      out.write("                        divPassword.addClass(\"has-success\");\r\n");
      out.write("                    }\r\n");
      out.write("                    \r\n");
      out.write("                    //패스워드 확인\r\n");
      out.write("                    if($('#passwordCheck').val()==\"\"){\r\n");
      out.write("                        modalContents.text(\"패스워드 확인을 입력하여 주시기 바랍니다.\");\r\n");
      out.write("                        modal.modal('show');\r\n");
      out.write("                        \r\n");
      out.write("                        divPasswordCheck.removeClass(\"has-success\");\r\n");
      out.write("                        divPasswordCheck.addClass(\"has-error\");\r\n");
      out.write("                        $('#passwordCheck').focus();\r\n");
      out.write("                        return false;\r\n");
      out.write("                    }else{\r\n");
      out.write("                        divPasswordCheck.removeClass(\"has-error\");\r\n");
      out.write("                        divPasswordCheck.addClass(\"has-success\");\r\n");
      out.write("                    }\r\n");
      out.write("                    \r\n");
      out.write("                    //패스워드 비교\r\n");
      out.write("                    if($('#password').val()!=$('#passwordCheck').val() || $('#passwordCheck').val()==\"\"){\r\n");
      out.write("                        modalContents.text(\"패스워드가 일치하지 않습니다.\");\r\n");
      out.write("                        modal.modal('show');\r\n");
      out.write("                        \r\n");
      out.write("                        divPasswordCheck.removeClass(\"has-success\");\r\n");
      out.write("                        divPasswordCheck.addClass(\"has-error\");\r\n");
      out.write("                        $('#passwordCheck').focus();\r\n");
      out.write("                        return false;\r\n");
      out.write("                    }else{\r\n");
      out.write("                        divPasswordCheck.removeClass(\"has-error\");\r\n");
      out.write("                        divPasswordCheck.addClass(\"has-success\");\r\n");
      out.write("                    }\r\n");
      out.write("                    \r\n");
      out.write("                    //이름\r\n");
      out.write("                    if($('#name').val()==\"\"){\r\n");
      out.write("                        modalContents.text(\"이름을 입력하여 주시기 바랍니다.\");\r\n");
      out.write("                        modal.modal('show');\r\n");
      out.write("                        \r\n");
      out.write("                        divName.removeClass(\"has-success\");\r\n");
      out.write("                        divName.addClass(\"has-error\");\r\n");
      out.write("                        $('#name').focus();\r\n");
      out.write("                        return false;\r\n");
      out.write("                    }else{\r\n");
      out.write("                        divName.removeClass(\"has-error\");\r\n");
      out.write("                        divName.addClass(\"has-success\");\r\n");
      out.write("                    }\r\n");
      out.write("                    \r\n");
      out.write("                    //별명\r\n");
      out.write("                    if($('#nickname').val()==\"\"){\r\n");
      out.write("                        modalContents.text(\"별명을 입력하여 주시기 바랍니다.\");\r\n");
      out.write("                        modal.modal('show');\r\n");
      out.write("                        \r\n");
      out.write("                        divNickname.removeClass(\"has-success\");\r\n");
      out.write("                        divNickname.addClass(\"has-error\");\r\n");
      out.write("                        $('#nickname').focus();\r\n");
      out.write("                        return false;\r\n");
      out.write("                    }else{\r\n");
      out.write("                        divNickname.removeClass(\"has-error\");\r\n");
      out.write("                        divNickname.addClass(\"has-success\");\r\n");
      out.write("                    }\r\n");
      out.write("                    \r\n");
      out.write("                    //이메일\r\n");
      out.write("                    if($('#email').val()==\"\"){\r\n");
      out.write("                        modalContents.text(\"이메일을 입력하여 주시기 바랍니다.\");\r\n");
      out.write("                        modal.modal('show');\r\n");
      out.write("                        \r\n");
      out.write("                        divEmail.removeClass(\"has-success\");\r\n");
      out.write("                        divEmail.addClass(\"has-error\");\r\n");
      out.write("                        $('#email').focus();\r\n");
      out.write("                        return false;\r\n");
      out.write("                    }else{\r\n");
      out.write("                        divEmail.removeClass(\"has-error\");\r\n");
      out.write("                        divEmail.addClass(\"has-success\");\r\n");
      out.write("                    }\r\n");
      out.write("                    \r\n");
      out.write("                    //휴대폰 번호\r\n");
      out.write("                    if($('#phoneNumber').val()==\"\"){\r\n");
      out.write("                        modalContents.text(\"휴대폰 번호를 입력하여 주시기 바랍니다.\");\r\n");
      out.write("                        modal.modal('show');\r\n");
      out.write("                        \r\n");
      out.write("                        divPhoneNumber.removeClass(\"has-success\");\r\n");
      out.write("                        divPhoneNumber.addClass(\"has-error\");\r\n");
      out.write("                        $('#phoneNumber').focus();\r\n");
      out.write("                        return false;\r\n");
      out.write("                    }else{\r\n");
      out.write("                        divPhoneNumber.removeClass(\"has-error\");\r\n");
      out.write("                        divPhoneNumber.addClass(\"has-success\");\r\n");
      out.write("                    }\r\n");
      out.write("                    \r\n");
      out.write("                \r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("        </script>\r\n");
      out.write("                <!--// 본문 들어가는 부분 -->\r\n");
      out.write("            <hr/>\r\n");
      out.write("            <!-- 푸터 들어가는 부분 -->\r\n");
      out.write("            \r\n");
      out.write("            <div>\r\n");
      out.write("                <p class=\"text-center\">\r\n");
      out.write("                    <small><strong>업체명</strong></small><br>\r\n");
      out.write("                    <small>대표 : 홍길동 ㆍ 주소 :  사거리 ㆍ 사업자등록번호:123-12-12345 ㆍ 전화 : 02-123-1234</small><br>\r\n");
      out.write("                    <small>Copyrightⓒ test.com All rights reserved.</small>\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--// 푸터 들어가는 부분 -->\r\n");
      out.write("        </div>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
